name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Create orphan snapshot
        run: |
          git checkout --orphan hf-sync
          git reset
          git add -A
          git commit -m "Snapshot for HF"

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HUGGING_SYNC }}
        run: |
          git push --force \
            https://marinooo:$HF_TOKEN@huggingface.co/spaces/marinooo/NaturalJob_app \
            HEAD:main
